---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm run lint:js
  - npm test

deploy:
  provider: heroku
  api_key: 
    secure: "921fdd12-7938-4078-8ade-b5b061c1139a"
  on: master
